🚧 UNFINISHED ❌ Update by generate-modules-sdk
Full error log:
╭──────────────────────────────────────────────────────────────────────────────╮
╰──────────────────────────────────────────────────────────────────────────────╯

[2K[1A[2K[1A[2K[G╭──────────────────────────────────────────────────────────────────────────────╮
│╭────────────────────────────────────────────────────────────────────────────╮│
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Initialized                                                           │││
││└──────────────────────────────────────────────────────────────────────────┘││
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Spawning Browser                                                      │││
│││[⧖] Connection from Collboard (http://localhost:3000/open-collboard)      │││
││└──────────────────────────────────────────────────────────────────────────┘││
││To open additional window http://localhost:3000/open-collboard              ││
│╰────────────────────────────────────────────────────────────────────────────╯│
╰──────────────────────────────────────────────────────────────────────────────╯

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G╭──────────────────────────────────────────────────────────────────────────────╮
│╭────────────────────────────────────────────────────────────────────────────╮│
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Initialized                                                           │││
││└──────────────────────────────────────────────────────────────────────────┘││
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Spawning Chrome                                                       │││
│││[⧖] Connection from Collboard (http://localhost:3000/open-collboard)      │││
││└──────────────────────────────────────────────────────────────────────────┘││
││To open additional window http://localhost:3000/open-collboard              ││
│╰────────────────────────────────────────────────────────────────────────────╯│
╰──────────────────────────────────────────────────────────────────────────────╯

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G╭──────────────────────────────────────────────────────────────────────────────╮
│╭────────────────────────────────────────────────────────────────────────────╮│
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Compiling                                                             │││
││└──────────────────────────────────────────────────────────────────────────┘││
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Spawning Chrome                                                       │││
│││[⧖] Connection from Collboard (http://localhost:3000/open-collboard)      │││
││└──────────────────────────────────────────────────────────────────────────┘││
││To open additional window http://localhost:3000/open-collboard              ││
│╰────────────────────────────────────────────────────────────────────────────╯│
╰──────────────────────────────────────────────────────────────────────────────╯

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G╭──────────────────────────────────────────────────────────────────────────────╮
│╭────────────────────────────────────────────────────────────────────────────╮│
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Compiling                                                             │││
││└──────────────────────────────────────────────────────────────────────────┘││
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[✔] Spawning Chrome                                                       │││
│││[⧖] Connection from Collboard (http://localhost:3000/open-collboard)      │││
││└──────────────────────────────────────────────────────────────────────────┘││
││To open additional window http://localhost:3000/open-collboard              ││
│╰────────────────────────────────────────────────────────────────────────────╯│
╰──────────────────────────────────────────────────────────────────────────────╯

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G╭──────────────────────────────────────────────────────────────────────────────╮
│╭────────────────────────────────────────────────────────────────────────────╮│
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Postprocessing                                                        │││
││└──────────────────────────────────────────────────────────────────────────┘││
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[✔] Spawning Chrome                                                       │││
│││[⧖] Connection from Collboard (http://localhost:3000/open-collboard)      │││
││└──────────────────────────────────────────────────────────────────────────┘││
││To open additional window http://localhost:3000/open-collboard              ││
│╰────────────────────────────────────────────────────────────────────────────╯│
╰──────────────────────────────────────────────────────────────────────────────╯

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G╭──────────────────────────────────────────────────────────────────────────────╮
│Error:  asset                                                                 │
│[1m[32m2022-7-24--20-4-19--ae8613be-4861-4bd2-a4ba-1994757495d5/main.min.js[39m[22m 396 KiB  │
│[1m[32m[emitted][39m[22m (name: main) 1 related asset                                        │
│runtime modules 670 bytes 3 modules                                           │
│modules by path [1m./node_modules/rxjs/_esm5/internal/[39m[22m 146 KiB 101 modules       │
│modules by path [1m./node_modules/waitasecond/dist/[39m[22m 16.9 KiB 11 modules          │
│modules by path [1m./src/[39m[22m 9.66 KiB                                               │
│  [1m./src/camera-tool.module.tsx[39m[22m 4.44 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m [1m[31m[1 error][39m[22m    │
│  [1m./src/camera-art.module.tsx[39m[22m 3.06 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m               │
│  [1m./src/utils/observeByHeartbeat.tsx[39m[22m 2.15 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m        │
│[1m./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js[39m[22m 54.7 KiB [1m[33m[built][39m[22m│
│ [1m[33m[code generated][39m[22m                                                             │
│[1m./node_modules/xyzt/dist/main.js[39m[22m 26.4 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m            │
│[1m./package.json[39m[22m 642 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m                             │
│[1m./node_modules/rxjs/_esm5/index.js[39m[22m 3.33 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m          │
│[1m./node_modules/tslib/tslib.es6.js[39m[22m 10 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m             │
│                                                                              │
│[1m[31mERROR[39m[22m in                                                                      │
│[1mC:\Users\me\work\collboard\collboard-camera\src\camera-tool.module.tsx[39m[22m        │
│[1m./src/camera-tool.module.tsx[39m[22m [1m[32m77:105-112[39m[22m                                       │
│[1m[tsl] [1m[31mERROR[39m[22m[1m in [22m                                                               │
│[1mC:\Users\me\work\collboard\collboard-camera\src\camera-tool.module.tsx(77,106)│
│      TS2339: Property 'inverse' does not exist on type                       │
│'BehaviorSubject<Transform>'.[39m[22m                                                 │
│                                                                              │
│webpack 5.35.1 compiled with [1m[31m1 error[39m[22m in 5602 ms                               │
╰──────────────────────────────────────────────────────────────────────────────╯

Error:  asset [1m[32m2022-7-24--20-4-19--ae8613be-4861-4bd2-a4ba-1994757495d5/main.min.js[39m[22m 396 KiB [1m[32m[emitted][39m[22m (name: main) 1 related asset
runtime modules 670 bytes 3 modules
modules by path [1m./node_modules/rxjs/_esm5/internal/[39m[22m 146 KiB 101 modules
modules by path [1m./node_modules/waitasecond/dist/[39m[22m 16.9 KiB 11 modules
modules by path [1m./src/[39m[22m 9.66 KiB
[1m./src/camera-tool.module.tsx[39m[22m 4.44 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m [1m[31m[1 error][39m[22m
[1m./src/camera-art.module.tsx[39m[22m 3.06 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
[1m./src/utils/observeByHeartbeat.tsx[39m[22m 2.15 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
[1m./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js[39m[22m 54.7 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
[1m./node_modules/xyzt/dist/main.js[39m[22m 26.4 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
[1m./package.json[39m[22m 642 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
[1m./node_modules/rxjs/_esm5/index.js[39m[22m 3.33 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
[1m./node_modules/tslib/tslib.es6.js[39m[22m 10 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m

[1m[31mERROR[39m[22m in [1mC:\Users\me\work\collboard\collboard-camera\src\camera-tool.module.tsx[39m[22m
[1m./src/camera-tool.module.tsx[39m[22m [1m[32m77:105-112[39m[22m
[1m[tsl] [1m[31mERROR[39m[22m[1m in C:\Users\me\work\collboard\collboard-camera\src\camera-tool.module.tsx(77,106)
TS2339: Property 'inverse' does not exist on type 'BehaviorSubject<Transform>'.[39m[22m

webpack 5.35.1 compiled with [1m[31m1 error[39m[22m in 5602 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\collboard-camera\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\collboard-camera\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\collboard-camera\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\collboard-camera\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\collboard-camera\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\collboard-camera\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\collboard-camera\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\collboard-camera\node_modules\webpack\lib\Watching.js:201:28)

🏭 This commit was automatically generated by generate-modules-sdk script.