🚧 Update to SDK 27.36.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🆗🍘👍🏿🛃

Full error log:
> @hejny/collboard-camera@0.3.14 lint
> tslint -p tsconfig.json

C:/Users/me/work/collboard/collboard-camera/src/camera-tool.module.tsx:38:35
ERROR: 38:35  comment-format  comment must start with a space
ERROR: 39:35  comment-format  comment must start with a space
ERROR: 65:19  comment-format  comment must start with a space
ERROR: 67:19  comment-format  comment must start with a space
ERROR: 69:19  comment-format  comment must start with a space